export enum ModalActionTypes {
  SHOW_CONNECT_MODAL = "CONNECT_MODAL",
  LOADING_METAMASK = "LOADING_METAMASK",
  WRONG_NETWORK = "WRONG_NETWORK",
  WRONG_ACCOUNT = "WRONG_ACCOUNT",
  METAMASK_NOT_FOUND = "METAMASK_NOT_FOUND",
  LOADING_TRANSACTION = "LOADING_TRANSACTION",
  LOADING_CANCEL_TRANSACTION = "LOADING_CANCEL_TRANSACTION",
}
